"""
    auth_app API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import auth_client
from auth_client.api.admin_api import AdminApi  # noqa: E501


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self):
        self.api = AdminApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auth_admin_v1_change_role_post(self):
        """Test case for auth_admin_v1_change_role_post

        Change Role  # noqa: E501
        """
        pass

    def test_auth_admin_v1_create_role_post(self):
        """Test case for auth_admin_v1_create_role_post

        Create Role  # noqa: E501
        """
        pass

    def test_auth_admin_v1_delete_role_delete(self):
        """Test case for auth_admin_v1_delete_role_delete

        Delete Role  # noqa: E501
        """
        pass

    def test_auth_admin_v1_get_all_roles_get(self):
        """Test case for auth_admin_v1_get_all_roles_get

        Get All Roles  # noqa: E501
        """
        pass

    def test_auth_admin_v1_set_user_role_post(self):
        """Test case for auth_admin_v1_set_user_role_post

        Set User Role  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
