"""
    auth_app API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import auth_client
from auth_client.model.change_role_in import ChangeRoleIn


class TestChangeRoleIn(unittest.TestCase):
    """ChangeRoleIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangeRoleIn(self):
        """Test ChangeRoleIn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChangeRoleIn()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
