"""
    auth_app API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest


class TestDeleteRoleIn(unittest.TestCase):
    """DeleteRoleIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteRoleIn(self):
        """Test DeleteRoleIn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteRoleIn()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
