"""
    auth_app API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

from auth_client.model.validation_error_detail_location import ValidationErrorDetailLocation

globals()["ValidationErrorDetailLocation"] = ValidationErrorDetailLocation


class TestValidationErrorDetail(unittest.TestCase):
    """ValidationErrorDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testValidationErrorDetail(self):
        """Test ValidationErrorDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ValidationErrorDetail()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
