"""
    Auth-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest


class TestGetPermissionsOut(unittest.TestCase):
    """GetPermissionsOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPermissionsOut(self):
        """Test GetPermissionsOut"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetPermissionsOut()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
