"""
    auth_app API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import auth_client
from auth_client.model.login_refresh_out import LoginRefreshOut


class TestLoginRefreshOut(unittest.TestCase):
    """LoginRefreshOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginRefreshOut(self):
        """Test LoginRefreshOut"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LoginRefreshOut()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
