"""
    auth_app API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import auth_client
from auth_client.model.http_error import HTTPError


class TestHTTPError(unittest.TestCase):
    """HTTPError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHTTPError(self):
        """Test HTTPError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HTTPError()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
