"""
    auth_app API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest


class TestChangePasswordIn(unittest.TestCase):
    """ChangePasswordIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangePasswordIn(self):
        """Test ChangePasswordIn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChangePasswordIn()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
