version: '3.9'

services:

  pg_movies:
    image: postgres:14.3
    env_file:
      - .env
    volumes:
      - pg_movies:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

  elastic_api:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data

  redis_api:
    image: redis:7.0.4

  pg_auth:
    image: postgres:14.3
    env_file:
      - auth.env
    volumes:
      - pg_auth:/var/lib/postgresql/data

  redis_auth:
    image: redis:7.0.4

volumes:
  pg_movies:
  pg_auth:
  es_data:

