"""add user fields

Revision ID: dd464d85a95a
Revises: c3b9b934f627
Create Date: 2022-09-11 00:54:14.929610

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dd464d85a95a"
down_revision = "c3b9b934f627"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("social_id", sa.String(length=64), nullable=True))
    op.add_column("users", sa.Column("name", sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, "users", ["social_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name")
    op.drop_column("users", "social_id")
    # ### end Alembic commands ###
